Update bash build script and build.cake to run on macos

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,133 +1,64 @@
 #!/usr/bin/env bash
 
-##########################################################################
-# This is the Cake bootstrapper script for Linux and OS X.
-# This file was downloaded from https://github.com/cake-build/resources
-# Feel free to change this file to fit your needs.
-##########################################################################
-
-# Define directories.
 SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-TOOLS_DIR=$SCRIPT_DIR/tools
-ADDINS_DIR=$TOOLS_DIR/addins
-MODULES_DIR=$TOOLS_DIR/modules
-NUGET_EXE=$TOOLS_DIR/nuget.exe
-CAKE_EXE=$TOOLS_DIR/Cake/Cake.exe
-PACKAGES_CONFIG=$TOOLS_DIR/packages.config
-PACKAGES_CONFIG_MD5=$TOOLS_DIR/packages.config.md5sum
-ADDINS_PACKAGES_CONFIG=$ADDINS_DIR/packages.config
-MODULES_PACKAGES_CONFIG=$MODULES_DIR/packages.config
-
-# Define md5sum or md5 depending on Linux/OSX
-MD5_EXE=
-if [[ "$(uname -s)" == "Darwin" ]]; then
-    MD5_EXE="md5 -r"
-else
-    MD5_EXE="md5sum"
-fi
+YELLOW='\033[1;33m'
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NO_COLOUR='\033[0m'
 
 # Define default arguments.
 SCRIPT="build.cake"
-TARGET="Default"
-CONFIGURATION="Release"
+TARGET="--target=Default"
+CONFIGURATION="--configuration=Release"
 WHERE=""
-VERBOSITY="verbose"
-DRYRUN=
-SHOW_VERSION=false
+VERBOSITY="--verbosity=verbose"
+DRYRUN=""
 SCRIPT_ARGUMENTS=()
 
 # Parse arguments.
 for i in "$@"; do
     case $1 in
         -s|--script) SCRIPT="$2"; shift ;;
-        -t|--target) TARGET="$2"; shift ;;
-        -c|--configuration) CONFIGURATION="$2"; shift ;;
-        -v|--verbosity) VERBOSITY="$2"; shift ;;
-		-w|--where) WHERE="$2"; shift ;;
-		-d|--dryrun) DRYRUN="-dryrun" ;;
-        --version) SHOW_VERSION=true ;;
+        -t|--target) TARGET="--target=$2"; shift ;;
+        -c|--configuration) CONFIGURATION="--configuration=$2"; shift ;;
+        -v|--verbosity) VERBOSITY="--verbosity=$2"; shift ;;
+		-w|--where) WHERE="--where=$2"; shift ;;
+		-d|--dryrun) DRYRUN="--dryrun" ;;
         --) shift; SCRIPT_ARGUMENTS+=("$@"); break ;;
         *) SCRIPT_ARGUMENTS+=("$1") ;;
     esac
     shift
 done
 
-# Make sure the tools folder exist.
-if [ ! -d "$TOOLS_DIR" ]; then
-  mkdir "$TOOLS_DIR"
-fi
+dotnet --version 2>&1 > /dev/null
 
-# Make sure that packages.config exist.
-if [ ! -f "$TOOLS_DIR/packages.config" ]; then
-    echo "Downloading packages.config..."
-    curl -Lsfo "$TOOLS_DIR/packages.config" http://cakebuild.net/download/bootstrapper/packages
-    if [ $? -ne 0 ]; then
-        echo "An error occured while downloading packages.config."
-        exit 1
-    fi
-fi
-
-# Download NuGet if it does not exist.
-if [ ! -f "$NUGET_EXE" ]; then
-    echo "Downloading NuGet..."
-    curl -Lsfo "$NUGET_EXE" https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
-    if [ $? -ne 0 ]; then
-        echo "An error occured while downloading nuget.exe."
-        exit 1
-    fi
-fi
-
-# Restore tools from NuGet.
-pushd "$TOOLS_DIR" >/dev/null
-if [ ! -f "$PACKAGES_CONFIG_MD5" ] || [ "$( cat "$PACKAGES_CONFIG_MD5" | sed 's/\r$//' )" != "$( $MD5_EXE "$PACKAGES_CONFIG" | awk '{ print $1 }' )" ]; then
-    find . -type d ! -name . | xargs rm -rf
-fi
-
-mono "$NUGET_EXE" install -ExcludeVersion
 if [ $? -ne 0 ]; then
-    echo "Could not restore NuGet tools."
-    exit 1
+    printf "${RED}Error:${NO_COLOUR} please install the dotnet cli\n"
+    exit 1;
 fi
 
-$MD5_EXE "$PACKAGES_CONFIG" | awk '{ print $1 }' >| "$PACKAGES_CONFIG_MD5"
+printf "${GREEN}Installing Cake.Tool with dotnet${NO_COLOUR}\n"
+OUTPUT=`dotnet tool install --global Cake.Tool 2>&1`
 
-popd >/dev/null
-
-# Restore addins from NuGet.
-if [ -f "$ADDINS_PACKAGES_CONFIG" ]; then
-    pushd "$ADDINS_DIR" >/dev/null
-
-    mono "$NUGET_EXE" install -ExcludeVersion
-    if [ $? -ne 0 ]; then
-        echo "Could not restore NuGet addins."
-        exit 1
-    fi
-
-    popd >/dev/null
+if [[ $? -eq 1 ]]; then
+    printf "${YELLOW}${OUTPUT}${NO_COLOUR}\n"
+elif [ $? -ne 0 ]; then
+    printf "${RED}Error:${NO_COLOUR} unable to install Cake.Tool with dotnet. command: dotnet tool install --global Cake.Tool\n"
+    exit 1;
 fi
 
-# Restore modules from NuGet.
-if [ -f "$MODULES_PACKAGES_CONFIG" ]; then
-    pushd "$MODULES_DIR" >/dev/null
+printf "${GREEN}Bootstrapping cake...${NO_COLOUR}\n"
+dotnet cake --bootstrap
 
-    mono "$NUGET_EXE" install -ExcludeVersion
-    if [ $? -ne 0 ]; then
-        echo "Could not restore NuGet modules."
-        exit 1
-    fi
-
-    popd >/dev/null
+if [ $? -ne "0" ]; then
+    printf "${RED}Error:${NO_COLOUR} failed to bootstrap cake. command: dotnet cake --bootstrap\n"
+    exit 1;
 fi
 
-# Make sure that Cake has been installed.
-if [ ! -f "$CAKE_EXE" ]; then
-    echo "Could not find Cake.exe at '$CAKE_EXE'."
-    exit 1
-fi
+printf "${GREEN}Executing cake build...${NO_COLOUR}\n"
+dotnet cake $SCRIPT --includeNetFramework=false $VERBOSITY $CONFIGURATION $WHERE $TARGET $DRYRUN "${SCRIPT_ARGUMENTS[@]}"
 
-# Start Cake
-if $SHOW_VERSION; then
-    exec mono "$CAKE_EXE" -version
-else
-    exec mono "$CAKE_EXE" $SCRIPT -verbosity=$VERBOSITY -configuration=$CONFIGURATION -where=$WHERE -target=$TARGET $DRYRUN "${SCRIPT_ARGUMENTS[@]}"
+if [ $? -ne 0 ]; then
+    printf "${RED}Error:${NO_COLOUR} Cake build failed. command: dotnet cake $SCRIPT --includeNetFramework=false $VERBOSITY $CONFIGURATION $WHERE $TARGET $DRYRUN ${SCRIPT_ARGUMENTS[@]}\n"
+    exit 1;
 fi
